### ISSUE TITLE
hosting problems !!!

### ISSUE THREAD

**Issue by DhruvDoshi** [bervProject/happy-birthday#205]
Mam I tried really hard to deploy this vue application used heroku, netify, versal-now, firebase and github pages but at the end I wasn't able to host the vue application

Could you please help me do this 

Well the application runs perfect on the localhost

**Comment by DhruvDoshi** [comment]
Please help me out with this issue

**Comment by berviantoleo** [comment]
Can you tell me the current problem? Should be easy to setup with netlify or [render.com](https://render.com/)

**Comment by berviantoleo** [comment]
I've modified the vue.config.js so easyly to switch between another deployment.

**Comment by DhruvDoshi** [comment]
![image](https://user-images.githubusercontent.com/41964565/82818478-68f2bc00-9ebc-11ea-89e5-e583382567d4.png)

**Comment by DhruvDoshi** [comment]
Still I have this problem after changing the vue config and rebuilding the system

**Comment by berviantoleo** [comment]
How you setup the vue config? @DhruvDoshi 

The error seems same you not setup correctly. Somehow for local, better just use serve command.

**Comment by berviantoleo** [comment]
Please just use this issue if still problem. I will reopen this, and close #206 .

**Comment by berviantoleo** [comment]
If you still confuse how to deploy. Please also read this.

https://cli.vuejs.org/guide/deployment.html#previewing-locally

**Comment by DhruvDoshi** [comment]
Thanks Bervproject/Happy-Birthday,

My project is up and running

**Comment by berviantoleo** [comment]
Nice, glad to hear that.
