### ISSUE TITLE
I am still facing error while building the system 

### ISSUE THREAD

**Issue by DhruvDoshi** [bervProject/happy-birthday#206]
![image](https://user-images.githubusercontent.com/41964565/82818586-92134c80-9ebc-11ea-9e77-558f33b5b2eb.png)

**Comment by DhruvDoshi** [comment]
could you please give my a mail over dhruvdoshi25071999@gmail.com them I will be able to share the screen with you and that could solve the problem with more precesion

**Comment by berviantoleo** [comment]
Ok @DhruvDoshi , you can try to share the videos too if you want.
You can contact me to bervianto.leo@gmail.com.
